version: v1
name: fda-records-agent-test
namespace: default
prompts:
- name: fda_question_extractor
  messages:
  - role: system
    content: 'Find FDA requests and extract them WITH ENOUGH CONTEXT to be self-contained.


      CRITICAL: Extract the ACTUAL request from the document, NOT examples or instructions.


      Include surrounding details so the request is SPECIFIC:

      - BAD: "Submit the data set" (WHICH data set?)

      - GOOD: "Submit the immunogenicity data set including all antibody test results"


      - BAD: "Please provide a report"

      - GOOD: "Please provide a manufacturing control strategy report addressing viral
      testing"


      Look for:

      - Questions with specifics ("Does X require Y?")

      - Commands with details ("Include glycosylation profiling data...")

      - Requests with context ("Provide safety data from Study 101...")


      DO NOT extract:

      - Vague requests without context

      - Statements ("This is...", "The document...")

      - Meta-descriptions ("Review...", "Extract...")

      - Headers, titles, boilerplate

      - Text from these instructions (like "request with enough context")


      Output format: <task>COPY THE EXACT FDA REQUEST FROM THE DOCUMENT</task>

      If no specific requests: <tasks></tasks>


      IMPORTANT: Extract ACTUAL requests from the FDA document, NOT placeholder text
      or examples.'
- name: fda_task_validator
  messages:
  - role: system
    content: 'You are validating if a text is a REAL, SPECIFIC FDA task.


      IMPORTANT: Most document chunks contain NO tasks. Be VERY strict.


      A REAL FDA task must:

      - Be SPECIFIC (not vague like "Submit the data set" or "Please provide a request")

      - Include enough context to understand WHAT is being requested

      - Be actionable on its own


      REJECT if:

      - Too vague ("Submit the report" - WHICH report?)

      - Generic meta-questions ("Please provide a question about the FDA")

      - Lacks specificity ("Please provide a request for information")

      - Statements or descriptions ("This is...", "The document...")

      - Headers or boilerplate text

      - FDA opinions without requests


      Answer with ONLY:

      <valid>yes</valid> if it''s a SPECIFIC, real FDA task

      <valid>no</valid> if it''s vague or not a real task'
- name: fda_answer_finder
  messages:
  - role: system
    content: 'Does the text contain an answer to the FDA''s request?


      CRITICAL: If you find an answer, you MUST extract the EXACT text from the document.


      Look for:

      - Specific data or numbers

      - Decisions or commitments

      - Direct responses with details


      DO NOT match if:

      - Text only acknowledges the request ("We received your question")

      - Text is unrelated (different topic)

      - Keywords match but content doesn''t actually answer


      Output format:

      If answered: <answered>yes</answered><quote>COPY THE EXACT TEXT FROM THE DOCUMENT
      HERE</quote>

      If not answered: <answered>no</answered>


      IMPORTANT: The <quote> tag must contain the ACTUAL text from the document, NOT
      placeholder text like ''relevant text''.'
rag:
  databases:
  - name: medical_db
    type: ChromaStore
    config:
      collection_name: medical_textbooks
      distance_function: cosine
      port: 8000
    embedding_strategies:
    - name: medical_embeddings
      type: OllamaEmbedder
      config:
        model: nomic-embed-text
        base_url: http://host.docker.internal:11434
        dimension: 768
        batch_size: 1
        auto_pull: true
        timeout: 60
      priority: 0
    retrieval_strategies:
    - name: medical_search
      type: BasicSimilarityStrategy
      config:
        distance_metric: cosine
        top_k: 6
      default: true
    default_embedding_strategy: medical_embeddings
    default_retrieval_strategy: medical_search
  - name: fda_letters_full
    type: ChromaStore
    config:
      collection_name: fda_letters_full
      distance_function: cosine
      port: 8000
    embedding_strategies:
    - name: fda_embeddings
      type: OllamaEmbedder
      config:
        model: nomic-embed-text
        base_url: http://host.docker.internal:11434
        dimension: 768
        batch_size: 1
        auto_pull: true
        timeout: 60
      priority: 0
    retrieval_strategies:
    - name: fda_search
      type: BasicSimilarityStrategy
      config:
        distance_metric: cosine
        top_k: 100
      default: true
    default_embedding_strategy: fda_embeddings
    default_retrieval_strategy: fda_search
  - name: fda_corpus_chunked
    type: ChromaStore
    config:
      collection_name: fda_corpus_chunked
      distance_function: cosine
      port: 8000
    embedding_strategies:
    - name: fda_embeddings
      type: OllamaEmbedder
      config:
        model: nomic-embed-text
        base_url: http://host.docker.internal:11434
        dimension: 768
        batch_size: 1
        auto_pull: true
        timeout: 60
      priority: 0
    retrieval_strategies:
    - name: fda_corpus_search
      type: BasicSimilarityStrategy
      config:
        distance_metric: cosine
        top_k: 3
      default: true
    default_embedding_strategy: fda_embeddings
    default_retrieval_strategy: fda_corpus_search
  data_processing_strategies:
  - name: medical_textbook_processor
    description: Simple processor for medical textbook text files - preserves paragraphs
      and semantic meaning
    parsers:
    - type: TextParser_Python
      config:
        chunk_size: 800
        chunk_overlap: 200
        chunk_strategy: paragraphs
        encoding: utf-8
        clean_text: false
        extract_metadata: true
      file_include_patterns:
      - '*.txt'
      priority: 10
    extractors:
    - type: KeywordExtractor
      config:
        algorithm: yake
        max_keywords: 15
        min_keyword_length: 3
      file_include_patterns:
      - '*.txt'
      priority: 10
    - type: ContentStatisticsExtractor
      config:
        include_readability: true
        include_vocabulary: true
      file_include_patterns:
      - '*.txt'
      priority: 20
  - name: fda_full_document_processor
    description: Processor for FDA documents with large chunks for question extraction
    parsers:
    - type: PDFParser_LlamaIndex
      config:
        chunk_size: 2000
        chunk_overlap: 400
        chunk_strategy: sentence
        extract_metadata: true
      file_include_patterns:
      - '*.pdf'
      priority: 10
    - type: TextParser_Python
      config:
        chunk_size: 2000
        chunk_overlap: 400
        chunk_strategy: paragraphs
        encoding: utf-8
        clean_text: false
        extract_metadata: true
      file_include_patterns:
      - '*.txt'
      priority: 10
    extractors:
    - type: KeywordExtractor
      config:
        algorithm: yake
        max_keywords: 10
        min_keyword_length: 3
      file_include_patterns:
      - '*.pdf'
      - '*.txt'
      priority: 10
  - name: fda_chunked_processor
    description: Processor for FDA documents with small chunks for RAG retrieval
    parsers:
    - type: PDFParser_LlamaIndex
      config:
        chunk_size: 800
        chunk_overlap: 200
        chunk_strategy: paragraphs
        extract_metadata: true
      file_include_patterns:
      - '*.pdf'
      priority: 10
    - type: TextParser_Python
      config:
        chunk_size: 800
        chunk_overlap: 200
        chunk_strategy: paragraphs
        encoding: utf-8
        clean_text: false
        extract_metadata: true
      file_include_patterns:
      - '*.txt'
      priority: 10
    extractors:
    - type: KeywordExtractor
      config:
        algorithm: yake
        max_keywords: 15
        min_keyword_length: 3
      file_include_patterns:
      - '*.pdf'
      - '*.txt'
      priority: 10
datasets:
- name: fda_letters
  data_processing_strategy: fda_full_document_processor
  database: fda_letters_full
  files:
  - 150290b3fbafec544a668b72dd11293d21ba97d436f51b61842d26b0147f94b9
- name: fda_corpus
  data_processing_strategy: fda_chunked_processor
  database: fda_corpus_chunked
  files: []
runtime:
  default_model: question_extractor
  models:
  - name: question_extractor
    description: Fast model for extracting FDA questions from documents
    provider: ollama
    model: qwen3:1.7b
    prompt_format: unstructured
    provider_config: {}
    prompts:
    - fda_question_extractor
  - name: task_validator
    description: Validates if extracted text is a real FDA task (2nd stage filter)
    provider: ollama
    model: qwen3:1.7b
    prompt_format: unstructured
    provider_config: {}
    prompts:
    - fda_task_validator
  - name: answer_finder
    description: Fast model for finding answers to FDA questions
    provider: ollama
    model: qwen3:1.7b
    prompt_format: unstructured
    provider_config: {}
    prompts:
    - fda_answer_finder
