version: v1
name: plain-app-project
namespace: default
prompts:
- name: document_assistant
  messages:
  - role: system
    content: |
      You are a knowledgeable AI Assistant with access to comprehensive documents.

      When answering questions:
      - Provide clear, accurate information based on the retrieved context
      - Explain concepts in simple, understandable terms
      - Always cite your sources when referencing specific information
      - If you're unsure or the information isn't in the context, say so
      - Maintain a helpful and professional tone

rag:
  databases:
  - name: document_db
    type: ChromaStore
    config:
      collection_name: documents
      distance_function: cosine
      port: 8000
    embedding_strategies:
    - name: document_embeddings
      type: OllamaEmbedder
      config:
        model: nomic-embed-text
        base_url: http://host.docker.internal:11434
        dimension: 768
        batch_size: 16
        auto_pull: true
        timeout: 60
      priority: 0
    retrieval_strategies:
    - name: document_search
      type: BasicSimilarityStrategy
      config:
        distance_metric: cosine
        top_k: 6
      default: true
    default_embedding_strategy: document_embeddings
    default_retrieval_strategy: document_search
  data_processing_strategies:
  - name: document_processor
    description: Simple processor for document files - preserves paragraphs
      and semantic meaning
    parsers:
    - type: TextParser_Python
      config:
        chunk_size: 800
        chunk_overlap: 200
        chunk_strategy: paragraphs
        encoding: utf-8
        clean_text: false
        extract_metadata: true
      file_include_patterns:
      - '*.txt'
      priority: 10
    - type: PDFParser_LlamaIndex
      config:
        chunk_size: 800
        chunk_overlap: 200
        chunk_strategy: paragraphs
        extract_metadata: true
      file_include_patterns:
      - '*.pdf'
      priority: 10
    extractors:
    - type: KeywordExtractor
      config:
        algorithm: yake
        max_keywords: 15
        min_keyword_length: 3
      file_include_patterns:
      - '*.txt'
      - '*.pdf'
      priority: 10
    - type: ContentStatisticsExtractor
      config:
        include_readability: true
        include_vocabulary: true
      file_include_patterns:
      - '*.txt'
      - '*.pdf'
      priority: 20
datasets:
- name: documents
  data_processing_strategy: document_processor
  database: document_db
  files: []
runtime:
  default_model: default
  models:
  - name: default
    description: Capable Qwen model for document Q&A synthesis
    provider: ollama
    model: gemma3:1b
    prompt_format: unstructured
    prompts:
      - document_assistant
    provider_config: {}
  - name: fast
    description: Fast small model for query generation and structured outputs
    provider: ollama
    model: gemma3:1b
    prompt_format: unstructured
    prompts:
      - document_assistant
    provider_config: {}
